### PR TITLE
Clean up javadoc

### PR DESCRIPTION
**Pull request by matthias-ronge**
Non-functional change, just improve javadoc

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
two remarks:
- some new lines containing trailing white spaces at end of line
- some changed javadoc parts are indent by tab others by space

**Comment by matthias-ronge** [comment]
The file is totally mixed, spaces and tabs. I can change all the javadoc to spaces. But, what about the code. Change or keep?

**Comment by henning-gerhardt** [comment]
Yes, I know :( Maybe first commit should the change of indent to space everywhere in the file then change the javadoc comments.

**Comment by henning-gerhardt** [comment]
Maybe this changes should be done without other changes pending as pull requests as now there is at least two conflicts and maybe pr #52 contains even more conflicts.

**Comment by matthias-ronge** [comment]
That’s the drawback of using one branch for one thing …

**Comment by matthias-ronge** [comment]
I just rebased the branch, but GitHub seems not to take notice of it.

**Comment by stweil** [comment]
Did you run `git push -f`?

**Comment by henning-gerhardt** [comment]
Maybe rebase base branch was not up to date? GitHub graphical network overview shows that branch was derivated at base c039d30 but current 2.x branch is on aa27a2d.

**Comment by matthias-ronge** [comment]
For whatever reason Eclipse’s _fetch from upstream_ fetches from _origin_, this is why I didn’t get the new `HEAD`. I tried another rebase but it fails with so many conflicts that this wasn’t an option. So here is a manual merge.

**Comment by henning-gerhardt** [comment]
Good to know that Eclipse is not so a good GIT tool. Maybe it is time to switch to a GIT console application ;) I will merge this changes now.

**Pull request merged**
